### ISSUE TITLE
how do i use this if i am building my project on backbone?

### ISSUE THREAD

**Issue by davis** [n-fuse/plugin-ember-hbs#1]
I am moving away from an npm/browserify stack to jspm, and I used to do things like

```
import template from './template.hbs'
```

how do I do a similar thing here?

**Comment by OrKoN** [comment]
@davis this plugin is for Ember.JS only because it uses `ember-template-compiler` instead of plain Handlebars. Are you using Backbone together with Ember somehow? 

If you want a plugin for plain Handlerbars you'll need to write your own plugin that uses handlebars instead of the ember-template-compiler. In this case the syntax would be:

```
import template from './template.hbs!'
```

or 

```
import template from './template.hbs!hbs'
```

or if you name your plugin differently:

```
import template from './template.hbs!pluginName'
```

If you don't want to have `!` you can wait for this https://github.com/systemjs/systemjs/issues/287 or pre-compile templates beforehand with the extension `.hbs.js`.

**Comment by davis** [comment]
ah, yeah. i just wrote my own plugin for this. thanks!
